# Generated by Django 5.0.7 on 2024-08-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='author_id',
            new_name='author',
        ),
    ]
